# Generated by Django 4.0.1 on 2022-01-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner', models.CharField(max_length=500, verbose_name='Имя Владельца Карты')),
                ('card_number', models.IntegerField(default=None, unique=True, verbose_name='Номер Карты')),
                ('card_status', models.CharField(choices=[('Activated', 'Активировано'), ('Deactivated', 'Деактивировано'), ('Expired', 'Просрочено')], default='Activated', max_length=100, verbose_name='Статус Карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата Выпуска Карты')),
                ('end_date', models.DateTimeField(verbose_name='Дата Истечения Срока Карты')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=500, verbose_name='Наименование Товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('used_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='webapp.card', verbose_name='Использованная Карта')),
            ],
        ),
    ]
