# Generated by Django 4.0.1 on 2022-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(unique=True, verbose_name='Номер Карты'),
        ),
    ]
