# Generated by Django 4.0.1 on 2022-01-08 16:48

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=webapp.models.random_numbers),
        ),
        migrations.AlterField(
            model_name='goods',
            name='used_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='webapp.card'),
        ),
    ]
