# Generated by Django 4.0.1 on 2022-01-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_product_alter_card_options_card_card_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
