# Generated by Django 4.0.1 on 2022-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.BooleanField(default=True),
        ),
    ]
