# Generated by Django 4.0.1 on 2022-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_card_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.BooleanField(default=True),
        ),
    ]
