# Generated by Django 4.0.1 on 2022-01-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_card_card_balance_alter_card_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
