# Generated by Django 4.0.1 on 2022-01-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='delete',
        ),
    ]
