# Generated by Django 4.0.1 on 2022-01-10 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_card_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата Появления Товара'),
            preserve_default=False,
        ),
    ]
